# Generated by Django on 2026-09-13
# Code & Architecture by BWP Engineering Team

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='room',
            field=models.IntegerField(blank=True, null=True, verbose_name='Room Number'),
        ),
        migrations.AddField(
            model_name='issue',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Task Notes'),
        ),
        migrations.CreateModel(
            name='IssueSupporter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_project', to='db.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_workspace', to='db.workspace')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_supporter', to='db.issue')),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_supporter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Issue Supporter',
                'verbose_name_plural': 'Issue Supporters',
                'db_table': 'issue_supporters',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='supporters',
            field=models.ManyToManyField(blank=True, related_name='supported_issues', through='db.IssueSupporter', through_fields=('issue', 'supporter'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='issuesupporter',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('issue', 'supporter'), name='issue_supporter_unique_issue_supporter_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='issuesupporter',
            unique_together={('issue', 'supporter', 'deleted_at')},
        ),
    ]
